// Mock data for trending reviews
export const mockTrending = [
  {
    id: 1,
    title: "Incredible Spider-Man: No Way Home",
    content: "A masterpiece of superhero cinema! The action sequences are breathtaking and the emotional moments hit hard.",
    rating: 5,
    upvotes: 234,
    author: {
      id: 101,
      name: "MovieBuff123",
      avatar: "https://i.pravatar.cc/150?img=1",
      isFollowing: false,
    },
    category: "Movies",
    createdAt: "2025-03-05T10:00:00Z",
  },
  {
    id: 2,
    title: "The Best Pizza in Town",
    content: "Authentic Italian pizza with a crispy crust. The margherita is simply divine!",
    rating: 5,
    upvotes: 189,
    author: {
      id: 102,
      name: "FoodieExplorer",
      avatar: "https://i.pravatar.cc/150?img=2",
      isFollowing: true,
    },
    category: "Food",
    createdAt: "2025-03-04T15:30:00Z",
  },
  {
    id: 3,
    title: "Samsung Galaxy S25 Ultra Review",
    content: "The camera is incredible, battery lasts two days. But it's very expensive.",
    rating: 4,
    upvotes: 156,
    author: {
      id: 103,
      name: "TechGuru",
      avatar: "https://i.pravatar.cc/150?img=3",
      isFollowing: false,
    },
    category: "Electronics",
    createdAt: "2025-03-03T08:15:00Z",
  },
  {
    id: 4,
    title: "Cozy Cafe with Great WiFi",
    content: "Perfect place to work. Great coffee and friendly staff.",
    rating: 4,
    upvotes: 112,
    author: {
      id: 104,
      name: "RemoteWorker",
      avatar: "https://i.pravatar.cc/150?img=4",
      isFollowing: false,
    },
    category: "Cafes",
    createdAt: "2025-03-02T11:45:00Z",
  },
];

// Mock data for leaderboard (top users by upvotes)
export const mockLeaderboard = [
  {
    rank: 1,
    id: 101,
    name: "MovieBuff123",
    avatar: "https://i.pravatar.cc/150?img=1",
    upvotes: 1250,
    reviewsCount: 87,
  },
  {
    rank: 2,
    id: 102,
    name: "FoodieExplorer",
    avatar: "https://i.pravatar.cc/150?img=2",
    upvotes: 980,
    reviewsCount: 64,
  },
  {
    rank: 3,
    id: 103,
    name: "TechGuru",
    avatar: "https://i.pravatar.cc/150?img=3",
    upvotes: 872,
    reviewsCount: 42,
  },
  {
    rank: 4,
    id: 104,
    name: "RemoteWorker",
    avatar: "https://i.pravatar.cc/150?img=4",
    upvotes: 654,
    reviewsCount: 31,
  },
  {
    rank: 5,
    id: 105,
    name: "AdventureSeeker",
    avatar: "https://i.pravatar.cc/150?img=5",
    upvotes: 543,
    reviewsCount: 29,
  },
];

// Mock recommendations (for "Recommended for You", "Because you liked", etc.)
export const mockRecommendations = [
  {
    id: 201,
    title: "Dune: Part Two",
    category: "Movies",
    rating: 4,
    image: "https://cdn.theplaylist.net/wp-content/uploads/2023/05/03103744/Dune-part-Two-.jpg",
    reason: "Because you watched Interstellar",
  },
  {
    id: 202,
    title: "Oppenheimer",
    category: "Movies",
    rating: 5,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1sInBjX1c4StpDRX-4xrJkmu9cJOW4W-VGA&s",
    reason: "Trending in Drama",
  },
  {
    id: 203,
    title: "Dhurandhar",
    category: "Movie",
    rating: 5,
    image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00478890-anhmpuxsbl-landscape.jpg",
    reason: "Because you liked Revange Movie",
  },
  {
    id: 204,
    title: "Sony WH-1000XM5",
    category: "Electronics",
    rating: 4.5,
    image: "https://pimwp.s3-accelerate.amazonaws.com/2023/04/image001-12.jpg",
    reason: "Popular in Electronics",
  },
  {
    id: 205,
    title: "Blue Bottle Coffee",
    category: "Food",
    rating: 4,
    image: "https://via.placeholder.com/300x200?text=Coffee",
    reason: "Because you reviewed Starbucks",
  },
  {
    id: 206,
    title: "The Last of Us",
    category: "TV Shows",
    rating: 5,
    image: "https://via.placeholder.com/300x200?text=TLOU",
    reason: "Based on your gaming interests",
  },
];